# Generated by Django 5.2.5 on 2025-10-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_categories_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="categories",
        ),
    ]
